// <auto-generated />
namespace MusicStreamingService.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class playlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(playlist));
        
        string IMigrationMetadata.Id
        {
            get { return "202110191433540_playlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
